### ISSUE TITLE
Clarification on `/acquisition/receiver/bandwidth`

### ISSUE THREAD

**Issue by jonschumacher** [MagneticParticleImaging/MDF#101]
While working on MPIMeasurements, I stumbled across `/acquisition/receiver/bandwidth`. Unfortunately, I was not able to figure out the meaning of this field from the specs. Does it describe the sampling rate, the first Nyquist zone limit, the 3 dB point (which I would actually call bandwidth, but which would also be encoded in the transfer function) or something that I did not think of?

**Comment by AvGladiss** [comment]
The `bandwidth` corresponds usually to half the sampling rate (Nyquist).

**Comment by tknopp** [comment]
So the Bruker scanner has 2.5 MS/s sampling rate and 1.25 MHz bandwidth.

**Comment by tknopp** [comment]
see https://github.com/MagneticParticleImaging/MPIMeasurements.jl/blob/edb7c1cfd849b9a75735c156482b49f7c097e67d/src/DAQ/Parameters.jl#L67

Not sure why we didn't use the sampling rate directly but I presume it it the case because in Brukerfiles it is called like this: 
https://github.com/MagneticParticleImaging/MPIFiles.jl/blob/master/src/Brukerfile.jl#L362
