### ISSUE TITLE
Parameter and HDF5 dataset

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MDF#22]
Should we mention, that a `parameter` in our document refers to a `HDF5 dataset`? Or maybe we could call it `HDF5 dataset` in the first place?

Either way I think we should point this out in the specificatinos, since `HDF5` also knows `attributes`.

**Comment by tknopp** [comment]
Makes sense to discuss this. Not sure we want to name everything a `dataset` since we have a lot of scalar values and a `dataset` for me kind of indicates that it is composed of several values.

**Comment by hofmannmartin** [comment]
On the other hand we currently store these scalars in `dataset`s don't we?

One could also think about storing these meta values, especially the flags as `attribute`. Whereas I just realize, that we do not specify, if `dataset` or `attribute` should be used.

**Comment by profix898** [comment]
Trying to catch up with the current MDF specification, I just hit this issue last week. Our default HDF5 implementation uses attributes for "meta data", i.e. measurement parameters, dimensions, etc., and datasets for actual data arrays (which typically means vectors, matrices or multi-dimensional arrays). I have no strong preference on using attributes vs datasets here, but we should certainly make a statement in the specification.

**Comment by tknopp** [comment]
Is there some good summary between the difference between the two?
I don't see any disadvantages when using datasets only.

But we should of course document this in the specification.

**Comment by profix898** [comment]
Probably thats also why we had a confusion about "groups" in HDF5. Attributes H5A are only associated with the "parent" dataset or group node, while a dataset H5D is a node itself, which can be referenced by id/path (or reused in another group by creating an object reference H5R within the file).

https://www.hdfgroup.org/HDF5/doc1.6/Attributes.html
https://www.hdfgroup.org/HDF5/doc1.6/Datasets.html

I cant find a simply comparison between the two or decent guidelines on how to use them. As the MDF design is done now, it would probably be more consistent to keep everything a dataset. Otherwise, the attributes in HDF5View (or similar tools) are accessible via their parents, but not listed as child objects in the tree. The alternative would be to associate the attributes with the actual dataset and not the group.

**Comment by hofmannmartin** [comment]
With future extensions in mind I think `datasets` are the way to go.

If we store certain parameters as `attributes` and then perform changes in the specs, which require us to change these to `datasets`, this would enforce us to lose backwards compatibility without any good reason.

Furthermore, we would have to treat `datasets` and `attributes` different, which could make sanity checks more involved, then necessary.
