### ISSUE TITLE
Brukerfile to MDF

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MDF#7]
from @MandyA:

2.       Is it planned to add methods that transform the Bruker data to MDF? If so, I could contribute our Matlab code in the institute that I wrote (it’s based on Tobis Julia Code anyway ;))

**Comment by tknopp** [comment]
Do you use a Julia implementation or have you converted this to Python?

So first, yes we have a Brukerfile to MDF conversion routine and we can share it with you. However, I don't see a need to integrate it into the package developed here. The sample code here is more for newcomers that want to use MPI data but do not have a scanner at hand.

**Comment by hofmannmartin** [comment]
I agree @tknopp . The MDF format and the related software project should be as scanner independent as possible. 

If there are a number of Bruker scanners out there we could start a independent software project for Brukerfile to MDF conversion.

**Comment by MandyA** [comment]
@tknopp: I have a matlab routine that is based on some line of a first version of your julia script.

I agree with both of you. MDF should be scanner independent. And it would be nice if everyone building scanners/doing hardware directly produces output in MDF format. However, I doubt that Bruker will feature this. So everyone owning a Bruker device will need to transform the data to MDF format to share data with others. Since the number of Bruker MPI customers will grow, I thought it might be nice to share the already done implementations to convert Bruker data to MDF. That might convince MPI beginners starting with a Bruker device to directly use MDF as data format.

**Comment by hofmannmartin** [comment]
To summarize:

1. We agree, that a conversion algorithm should not be part of the MDF package.
2. As the number of Bruker Scanners will grow an additional project to convert Brukerfiles to MDF could be started at some point.

**Comment by tknopp** [comment]
Te conversion routine alone is pretty boring. People would also want a full-featured reconstruction library that operates on MDF (or Brukerfile). But lets first look if there is a greater interest in this. We could think about open sourcing our reconstruction library but I would only do this if
 - there is at least anybody out there using it (Mandy hint hint)
 - it stays in Julia :-)
